import type { ModelDefinition } from "../../domain/model/types";

export const deepseekV4Models: ModelDefinition[] = [
  {
    family: "deepseek-v4",
    id: "deepseek-v4-flash",
    displayName: "DeepSeek-V4-Flash",
    architectureKind: "compressed-moe",
    formulaStrategyId: "deepseek-v4-compressed-moe",
    configSource: "docs/deepseek_v4/config/DeepSeek-V4-Flash-config.json",
    parameterSourceUrl: "https://huggingface.co/deepseek-ai/DeepSeek-V4-Flash/blob/main/config.json",
    weightSourceUrl: "https://huggingface.co/deepseek-ai/DeepSeek-V4-Flash",
    recommendedPrecision: {
      label: "FP8 weights / FP4 experts / BF16 activations",
      bytesPerWeight: 1,
      bytesPerActivation: 2,
      bytesPerExpert: 0.5
    },
    contextLimit: 1048576,
    decoderLayers: 43,
    hiddenSize: 4096,
    attentionHeads: 64,
    kvHeads: 1,
    headDim: 512,
    qLoraRank: 1024,
    oLoraRank: 1024,
    oGroups: 8,
    indexHeads: 64,
    indexHeadDim: 128,
    indexTopk: 512,
    slidingWindow: 128,
    csaCompressRate: 4,
    hcaCompressRate: 128,
    moeExperts: 128,
    activeExperts: 6,
    moeIntermediateSize: 2048,
    csaLayerCount: 21,
    hcaLayerCount: 20,
    slidingLayerCount: 2,
    totalParamsB: 200,
    totalExpertParamsB: 170,
    estimatedWeightsGb: 145.82
  },
  {
    family: "deepseek-v4",
    id: "deepseek-v4-pro",
    displayName: "DeepSeek-V4-Pro",
    architectureKind: "compressed-moe",
    formulaStrategyId: "deepseek-v4-compressed-moe",
    configSource: "docs/deepseek_v4/config/DeepSeek-V4-Pro-config.json",
    parameterSourceUrl: "https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro/blob/main/config.json",
    weightSourceUrl: "https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro",
    recommendedPrecision: {
      label: "FP8 weights / FP4 experts / BF16 activations",
      bytesPerWeight: 1,
      bytesPerActivation: 2,
      bytesPerExpert: 0.5
    },
    contextLimit: 1048576,
    decoderLayers: 61,
    hiddenSize: 7168,
    attentionHeads: 128,
    kvHeads: 1,
    headDim: 512,
    qLoraRank: 1536,
    oLoraRank: 1024,
    oGroups: 16,
    indexHeads: 64,
    indexHeadDim: 128,
    indexTopk: 1024,
    slidingWindow: 128,
    csaCompressRate: 4,
    hcaCompressRate: 128,
    moeExperts: 384,
    activeExperts: 6,
    moeIntermediateSize: 3072,
    csaLayerCount: 30,
    hcaLayerCount: 31,
    slidingLayerCount: 0,
    totalParamsB: 1500,
    totalExpertParamsB: 1400,
    estimatedWeightsGb: 799.31
  }
];
