import type { ModelDefinition } from "../../domain/model/types";

export const gemma4Models: ModelDefinition[] = [
  {
    family: "gemma-4",
    id: "gemma-4-e2b-it",
    displayName: "Gemma-4-E2B",
    architectureKind: "dense-decoder",
    formulaStrategyId: "dense-decoder-transformer",
    configSource: "docs/gemma_4/config/gemma-4-E2B-it-config.json",
    parameterSourceUrl: "https://huggingface.co/google/gemma-4-E2B-it/blob/main/config.json",
    weightSourceUrl: "https://huggingface.co/google/gemma-4-E2B-it",
    recommendedPrecision: { label: "BF16", bytesPerWeight: 2, bytesPerActivation: 2, bytesPerExpert: 2 },
    contextLimit: 131072,
    decoderLayers: 35,
    hiddenSize: 1536,
    attentionHeads: 8,
    kvHeads: 1,
    headDim: 256,
    qLoraRank: 0, oLoraRank: 0, oGroups: 0,
    indexHeads: 0, indexHeadDim: 0, indexTopk: 0,
    csaCompressRate: 0, hcaCompressRate: 0,
    moeExperts: 0, activeExperts: 0, moeIntermediateSize: 0,
    csaLayerCount: 0, hcaLayerCount: 0,
    slidingWindow: 512,
    slidingLayerCount: 28,
    intermediateSize: 6144,
    fullAttentionLayerCount: 7,
    slidingAttentionLayerCount: 28,
    globalHeadDim: 512,
    numGlobalKeyValueHeads: 1,
    attentionKEqV: false,
    hiddenActivation: "gelu_pytorch_tanh",
    checkpointParamsB: 5.1,
    textBackboneParamsB: 4.628569344,
    tokenLookupParamsB: 2.751463424,
    perLayerEmbeddingSize: 256,
    kvSharedLayerCount: 20,
    independentSlidingAttentionLayerCount: 12,
    independentFullAttentionLayerCount: 3,
    doubleWideMlpInKvSharedLayers: true,
    totalParamsB: 5.1,
    totalExpertParamsB: 0,
    estimatedWeightsGb: 10.2
  },
  {
    family: "gemma-4",
    id: "gemma-4-e4b-it",
    displayName: "Gemma-4-E4B",
    architectureKind: "dense-decoder",
    formulaStrategyId: "dense-decoder-transformer",
    configSource: "docs/gemma_4/config/gemma-4-E4B-it-config.json",
    parameterSourceUrl: "https://huggingface.co/google/gemma-4-E4B-it/blob/main/config.json",
    weightSourceUrl: "https://huggingface.co/google/gemma-4-E4B-it",
    recommendedPrecision: { label: "BF16", bytesPerWeight: 2, bytesPerActivation: 2, bytesPerExpert: 2 },
    contextLimit: 131072,
    decoderLayers: 42,
    hiddenSize: 2560,
    attentionHeads: 8,
    kvHeads: 2,
    headDim: 256,
    qLoraRank: 0, oLoraRank: 0, oGroups: 0,
    indexHeads: 0, indexHeadDim: 0, indexTopk: 0,
    csaCompressRate: 0, hcaCompressRate: 0,
    moeExperts: 0, activeExperts: 0, moeIntermediateSize: 0,
    csaLayerCount: 0, hcaLayerCount: 0,
    slidingWindow: 512,
    slidingLayerCount: 35,
    intermediateSize: 10240,
    fullAttentionLayerCount: 7,
    slidingAttentionLayerCount: 35,
    globalHeadDim: 512,
    numGlobalKeyValueHeads: 2,
    attentionKEqV: false,
    hiddenActivation: "gelu_pytorch_tanh",
    checkpointParamsB: 8,
    textBackboneParamsB: 7.463013376,
    tokenLookupParamsB: 3.489660928,
    perLayerEmbeddingSize: 256,
    kvSharedLayerCount: 18,
    independentSlidingAttentionLayerCount: 20,
    independentFullAttentionLayerCount: 4,
    doubleWideMlpInKvSharedLayers: false,
    totalParamsB: 8,
    totalExpertParamsB: 0,
    estimatedWeightsGb: 16
  },
  {
    family: "gemma-4",
    id: "gemma-4-12b-it",
    displayName: "Gemma-4-12B-it",
    architectureKind: "dense-decoder",
    formulaStrategyId: "dense-decoder-transformer",
    configSource: "docs/gemma_4/config/gemma-4-12B-it-config.json",
    parameterSourceUrl: "https://huggingface.co/google/gemma-4-12B-it/blob/main/config.json",
    weightSourceUrl: "https://huggingface.co/google/gemma-4-12B-it",
    recommendedPrecision: {
      label: "BF16",
      bytesPerWeight: 2,
      bytesPerActivation: 2,
      bytesPerExpert: 2
    },
    contextLimit: 262144,
    decoderLayers: 48,
    hiddenSize: 3840,
    attentionHeads: 16,
    kvHeads: 8,
    headDim: 256,

    // —— compressed-moe 字段（不适用，填 0） ——
    qLoraRank: 0,
    oLoraRank: 0,
    oGroups: 0,
    indexHeads: 0,
    indexHeadDim: 0,
    indexTopk: 0,
    csaCompressRate: 0,
    hcaCompressRate: 0,
    moeExperts: 0,
    activeExperts: 0,
    moeIntermediateSize: 0,
    csaLayerCount: 0,
    hcaLayerCount: 0,

    // —— 通用 ——
    slidingWindow: 1024,
    slidingLayerCount: 40,

    // —— dense-decoder 专用 ——
    intermediateSize: 15360,
    fullAttentionLayerCount: 8,
    slidingAttentionLayerCount: 40,
    globalHeadDim: 512,
    numGlobalKeyValueHeads: 1,
    attentionKEqV: true,
    hiddenActivation: "gelu_pytorch_tanh",

    checkpointParamsB: 11.91,
    textBackboneParamsB: 11.91,
    tokenLookupParamsB: 0,
    totalParamsB: 11.91,
    totalExpertParamsB: 0,
    estimatedWeightsGb: 23.82
  },
  {
    family: "gemma-4",
    id: "gemma-4-26b-a4b-it",
    displayName: "google/gemma-4-26B-A4B-it",
    architectureKind: "dense-decoder-moe",
    formulaStrategyId: "dense-decoder-moe",
    configSource: "docs/gemma_4/config/gemma-4-26B-A4B-it-config.json",
    parameterSourceUrl: "https://huggingface.co/google/gemma-4-26B-A4B-it/blob/main/config.json",
    weightSourceUrl: "https://huggingface.co/google/gemma-4-26B-A4B-it",
    recommendedPrecision: {
      label: "BF16",
      bytesPerWeight: 2,
      bytesPerActivation: 2,
      bytesPerExpert: 2
    },
    contextLimit: 262144,
    decoderLayers: 30,
    hiddenSize: 2816,
    attentionHeads: 16,
    kvHeads: 8,
    headDim: 256,

    // —— compressed-moe 字段（不适用，填 0） ——
    qLoraRank: 0,
    oLoraRank: 0,
    oGroups: 0,
    indexHeads: 0,
    indexHeadDim: 0,
    indexTopk: 0,
    csaCompressRate: 0,
    hcaCompressRate: 0,
    csaLayerCount: 0,
    hcaLayerCount: 0,

    // —— MoE FFN ——
    moeExperts: 128,
    activeExperts: 8,
    moeIntermediateSize: 704,

    // —— 通用 ——
    slidingWindow: 1024,
    slidingLayerCount: 25,

    // —— dense-decoder-moe 专用 ——
    intermediateSize: 2112,
    fullAttentionLayerCount: 5,
    slidingAttentionLayerCount: 25,
    globalHeadDim: 512,
    numGlobalKeyValueHeads: 2,
    attentionKEqV: true,
    hiddenActivation: "gelu_pytorch_tanh",

    checkpointParamsB: 26,
    textBackboneParamsB: 26,
    tokenLookupParamsB: 0,
    totalParamsB: 26,
    totalExpertParamsB: 22.84,
    estimatedWeightsGb: 52
  }
];
